// dsh-whiteboard 构建脚本：
//   1) esbuild 将 src/app.js 打包（内联 @excalidraw/excalidraw 全部依赖，
//      external 仅 react 系列 —— 运行时由 DSH ModuleLoader 提供）；
//   2) 产物包装为 window.__ModuleLoader__.load({id, factory}) 写入 lib/client.js；
//      factory 的 require 包装一层: "util"（graphlib 引用 node 内置）→ 本地 shim；
//   3) 复制 excalidraw.css + 字体到 lib/vendor（host 静态路由 serve）。
// 用法: node build.mjs [--watch]
import { build } from 'esbuild'
import { cpSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(fileURLToPath(import.meta.url))
const EXC = join(root, 'node_modules/@excalidraw/excalidraw/dist/prod')
const TMP = join(root, 'lib/.client.bundle.js')
const OUT = join(root, 'lib/client.js')
const VENDOR = join(root, 'lib/vendor')

// ── 静态资源 ──
function copyAssets() {
  mkdirSync(VENDOR, { recursive: true })
  const css = readFileSync(join(EXC, 'index.css'), 'utf8')
    .replace(/url\(\.\/fonts\//g, 'url(/dsh-whiteboard/vendor/fonts/')
  writeFileSync(join(VENDOR, 'excalidraw.css'), css)
  cpSync(join(EXC, 'fonts'), join(VENDOR, 'fonts'), { recursive: true })
}

// ── esbuild plugins ──
// excalidraw 动态 import 的语言包只保留 en / zh-CN，其余空模块（省 ~1.6MB）
function wbPlugins() {
  return [{
    name: 'dsh-whiteboard-locale-trim',
    setup(build) {
      build.onResolve({ filter: /^\.\/locales\// }, (args) => {
        if (/^\.\/locales\/(en|zh-CN)(\.|-)/.test(args.path)) return undefined // 保留（en.json / zh-CN.json 等）
        return { path: args.path, namespace: 'wb-empty-locale' }
      })
      build.onLoad({ filter: /.*/, namespace: 'wb-empty-locale' },
        () => ({ contents: 'module.exports = {}' }))
    },
  }]
}

function bundleOptions() {
  return {
    entryPoints: [join(root, 'src/app.js')],
    bundle: true,
    format: 'cjs',
    target: 'es2020',
    jsx: 'transform',
    minify: true,
    external: ['react', 'react-dom', 'react/jsx-runtime', 'react-dom/client', '@excalidraw/excalidraw'], // excalidraw 拆到独立 bundle
    outfile: TMP,
    logLevel: 'info',
    plugins: wbPlugins(),
  }
}

// factory 包装：提供 module/exports；require 拦截 "util" → 本地 shim
function wrap(bundle) {
  return [
    '// dsh-whiteboard client bundle — generated by build.mjs, do not edit.',
    '// 改 src/app.js 后运行 node build.mjs（或 --watch）。',
    'window.__ModuleLoader__.load({',
    "  id: 'dsh-whiteboard',",
    '  factory: (__wbRequire) => {',
    "    var require = (spec) => spec === 'util'",
    '      ? { inspect: (v) => String(v) } : __wbRequire(spec)',
    '    var module = { exports: {} }',
    '    var exports = module.exports',
    bundle,
    'return module.exports',
    '  }',
    '})',
    ''
  ].join('\n')
}

async function emitBundle() {
  const bundle = readFileSync(TMP, 'utf8')
  const wrapped = wrap(bundle)
  writeFileSync(OUT, wrapped)
  rmSync(TMP, { force: true })
  console.log('[dsh-whiteboard] lib/client.js ' + (Buffer.byteLength(wrapped) / 1024).toFixed(0) + ' KB')
}

// ── Excalidraw 独立 bundle（延迟加载）──
// wrapper：require 从 window.__WB_REACT 取 react 系列（主 bundle 注入，保证同一实例）；
// util → shim；执行完毕挂 window.__WBExcalidraw
async function buildVendor() {
  const vendorTmp = join(root, 'lib/.vendor.bundle.js')
  await build({
    entryPoints: [join(root, 'src/excalidraw-entry.js')],
    bundle: true,
    format: 'cjs',
    target: 'es2020',
    jsx: 'transform',
    minify: true,
    external: ['react', 'react-dom', 'react/jsx-runtime', 'react-dom/client'],
    outfile: vendorTmp,
    logLevel: 'info',
    plugins: wbPlugins(),
  })
  const bundle = readFileSync(vendorTmp, 'utf8')
  const wrapped = [
    '// dsh-whiteboard excalidraw vendor — generated by build.mjs, do not edit.',
    '(function () {',
    '  var require = function (spec) {',
    '    if (spec === "react" || spec === "react/jsx-runtime" || spec === "react-dom" || spec === "react-dom/client") {',
    '      var r = window.__WB_REACT && window.__WB_REACT[spec]',
    '      if (r) return r',
    '      if (spec === "react" && window.__WB_REACT && window.__WB_REACT.react) return window.__WB_REACT.react',
    '      throw new Error("excalidraw-lib: react not ready for " + spec)',
    '    }',
    '    if (spec === "util") return { inspect: function (v) { return String(v) } }',
    '    throw new Error("excalidraw-lib: unexpected require " + spec)',
    '  }',
    '  var module = { exports: {} }',
    '  var exports = module.exports',
    bundle,
    '  window.__WBExcalidraw = { Excalidraw: (module.exports && module.exports.Excalidraw) || exports.Excalidraw }',
    '})();',
    ''
  ].join('\n')
  writeFileSync(join(root, 'lib/vendor/excalidraw-lib.js'), wrapped)
  rmSync(vendorTmp, { force: true })
  console.log('[dsh-whiteboard] lib/vendor/excalidraw-lib.js ' + (Buffer.byteLength(wrapped) / 1024).toFixed(0) + ' KB')
}

async function once() {
  copyAssets()
  await build(bundleOptions())
  await emitBundle()
  await buildVendor()
}

const watch = process.argv.includes('--watch')
if (watch) {
  copyAssets()
  await buildVendor()
  const ctx = await build({
    ...bundleOptions(),
    watch: {
      onRebuild: async (err) => {
        if (err) { console.error('[dsh-whiteboard] rebuild failed', err); return }
        try { await emitBundle() } catch (e) { console.error('[dsh-whiteboard] wrap failed', e) }
      },
    },
  })
  console.log('[dsh-whiteboard] watching src/app.js ...')
  const stop = () => ctx.dispose()
  process.on('SIGINT', stop)
  process.on('SIGTERM', stop)
} else {
  await once()
}