// dsh-safe-mode host half — 安全模式面板。
//
// 背景: 当某个插件的 host 代码(lib/index.js)被改坏时,dsh 的 Loader 会
// 整体回滚启动(任一条目失败 = 整棵树失败),用户连 Web 界面都进不去。
// dsh-safe 脚本(dsh-dock/dsh-safe)会在启动前体检所有插件,把坏插件写入
// ~/.dsh/profiles/<profile>/safe-mode.overlay.yml(格式为 patch 覆盖层,
// `- id: xxx / disabled: true`),然后以 `dsh web --patch <overlay>` 启动:
// 被隔离的条目 disabled=true,Loader 连它的模块都不会 import,坏插件不影响启动。
//
// 本插件负责安全模式下的「界面」:
//   * tapIndex 注入横幅 —— 页面顶部提示被隔离的插件,提供
//     「解除隔离并重启 / 移除此插件」入口(不依赖 slot 系统,最可靠);
//   * GET  /dsh-safe/status   查询隔离状态;
//   * POST /dsh-safe/heal     {all:true} 或 {id} —— 解除隔离(先做语法体检)并重启;
//   * POST /dsh-safe/remove   {pkg} —— 从 profile 移除该插件并重启。
//
// ⚠️ 本插件是全仓库「最不该被 AI 修改」的文件之一: 它自身若损坏,
// 安全模式就没有界面了。代码刻意保持简单、防御式(所有路由 try/catch)。
import { spawn, spawnSync } from 'node:child_process'
import { appendFileSync, existsSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const NAME = 'dsh-safe-mode'
const DIAG = '/tmp/dsh-safe-mode.log'

function log(...parts) {
  try {
    appendFileSync(DIAG, `${new Date().toISOString()} ${parts.join(' ')}\n`, 'utf8')
  } catch {
    /* 日志失败不影响功能 */
  }
}

// ── 路径 ─────────────────────────────────────────────────────────────────────
function paths(ctx) {
  const homePath = ctx.get('dshHomePath')
  const profileName = process.env.DSH_SAFE_PROFILE || 'web'
  let profileDir
  try {
    // dshHomePath(...segments) = <DSH_HOME>/<segments>,由 dsh-app-boot 提供
    profileDir = typeof homePath === 'function'
      ? homePath('profiles', profileName)
      : join(process.env.DSH_HOME || process.env.HOME || '', '.dsh', 'profiles', profileName)
  } catch {
    profileDir = join(process.env.DSH_HOME || process.env.HOME || '', '.dsh', 'profiles', profileName)
  }
  return {
    profileName,
    profileDir,
    overlay: join(profileDir, 'safe-mode.overlay.yml'),
    state: join(profileDir, 'safe-mode.state.json')
  }
}

// ── 隔离文件读写 ─────────────────────────────────────────────────────────────
// overlay 是 dsh 真正读取的文件(patch 覆盖层): 每条 `- id: xxx / disabled: true`
// 对应一个被隔离的 bundle 行。state 是给本插件/脚本看的 JSON(记录原因、时间)。
// 注意: overlay 永远不删除,空时写 '[]'(若删除,而进程是以 --patch <它> 启动的,
// 重启按钮会因文件缺失而启动失败)。
function readOverlayIds(file) {
  if (!existsSync(file)) return []
  const text = readFileSync(file, 'utf8')
  const ids = []
  for (const m of text.matchAll(/^\s*(?:-\s*)?id:\s*([^\s#]+)/gm)) ids.push(m[1].trim())
  return ids
}

function writeOverlay(file, ids) {
  const head = '# dsh-safe quarantine overlay — generated by dsh-safe / dsh-safe-mode. Do not edit by hand.\n'
  if (ids.length === 0) {
    writeFileSync(file, head + '[]\n', 'utf8')
    return
  }
  // patch 格式: 非 insert 条目 = 顶层 id + 覆盖字段(与 loader 写回 / dsh-plugin-manager
  // 持久化的格式一致;没有 `edit:` 包装层)
  writeFileSync(file, head + ids.map((id) => `- id: ${id}\n  disabled: true`).join('\n') + '\n', 'utf8')
}

function readState(file) {
  try {
    return JSON.parse(readFileSync(file, 'utf8'))
  } catch {
    return { quarantined: [] }
  }
}

function writeState(file, quarantined) {
  writeFileSync(file, JSON.stringify({ quarantined, updatedAt: new Date().toISOString() }, null, 2) + '\n', 'utf8')
}

// ── 语法体检(解除隔离前的安全检查) ─────────────────────────────────────────
function checkJs(file) {
  const r = spawnSync(process.execPath, ['--check', file], { encoding: 'utf8' })
  if (r.status === 0) return { ok: true }
  // ESM 兜底: 部分 node 版本 --check 按 CJS 解析,换 stdin + --input-type=module 再试
  let src
  try {
    src = readFileSync(file, 'utf8')
  } catch {
    return { ok: false, err: `无法读取 ${file}` }
  }
  const r2 = spawnSync(process.execPath, ['--check', '--input-type=module'], { input: src, encoding: 'utf8' })
  if (r2.status === 0) return { ok: true }
  const err = (r2.stderr || r.stderr || '').split('\n').find(Boolean) || 'syntax error'
  return { ok: false, err: err.slice(0, 300) }
}

function checkPluginSyntax(pkg, profileDir) {
  const dir = join(profileDir, 'node_modules', pkg)
  if (!existsSync(dir)) return { ok: true } // 包已不在,无需体检
  let manifest
  try {
    manifest = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8'))
  } catch (e) {
    return { ok: false, err: `package.json 解析失败: ${e.message}` }
  }
  const mainRel = manifest.main || 'lib/index.js'
  const mainPath = join(dir, mainRel)
  if (existsSync(mainPath)) {
    const r = checkJs(mainPath)
    if (!r.ok) return { ok: false, err: `${mainRel} 语法错误: ${r.err}` }
  } else if (manifest.main) {
    return { ok: false, err: `main 文件不存在: ${mainRel}` }
  }
  const clientPath = join(dir, 'lib/client.js')
  if (existsSync(clientPath)) {
    const r = checkJs(clientPath)
    if (!r.ok) return { ok: false, err: `lib/client.js 语法错误: ${r.err}` }
  }
  return { ok: true }
}

// ── HTTP 工具 ────────────────────────────────────────────────────────────────
function sendJson(res, code, obj) {
  const body = JSON.stringify(obj)
  try {
    res.writeHead(code, {
      'Content-Type': 'application/json; charset=utf-8',
      'Content-Length': Buffer.byteLength(body)
    })
    res.end(body)
  } catch {
    /* 连接已断开 */
  }
}

function readBody(req) {
  return new Promise((resolve, reject) => {
    let data = ''
    req.on('data', (chunk) => {
      data += chunk
      if (data.length > 64 * 1024) {
        req.destroy()
        reject(new Error('body too large'))
      }
    })
    req.on('end', () => {
      try {
        resolve(data ? JSON.parse(data) : {})
      } catch (e) {
        reject(e)
      }
    })
    req.on('error', reject)
  })
}

// ── 重启(与 dsh-system-restart 同款: 回答浏览器后拉新进程再退出) ───────────
function restartSoon() {
  setTimeout(() => {
    try {
      log('restarting: argv=' + process.argv.slice(1).join(' '))
      const child = spawn(process.execPath, process.argv.slice(1), {
        detached: true,
        stdio: 'inherit',
        env: process.env,
        cwd: process.cwd()
      })
      child.unref()
    } catch (error) {
      log('restart failed: ' + (error instanceof Error ? error.message : String(error)))
    }
    process.exit(0)
  }, 800)
}

// ── 状态计算 ─────────────────────────────────────────────────────────────────
function computeStatus(p) {
  const ids = readOverlayIds(p.overlay)
  const state = readState(p.state)
  const quarantined = ids.map((id) => {
    const s = (state.quarantined || []).find((q) => q.id === id)
    return { id, pkg: s?.pkg || id, reason: s?.reason || '', at: s?.at || '' }
  })
  return { ok: true, profile: p.profileName, overlayExists: existsSync(p.overlay), quarantined }
}

// ── 横幅注入(tapIndex,不依赖 slot/客户端模块,最可靠) ──────────────────────
const BANNER_CSS = `
<style data-dsh-safe-mode="banner">
#dsh-safe-banner{position:fixed;top:12px;left:50%;transform:translateX(-50%);z-index:2147483000;max-width:min(680px,calc(100vw - 24px));box-sizing:border-box;font:13px/1.55 -apple-system,BlinkMacSystemFont,'Segoe UI','PingFang SC','Microsoft YaHei',sans-serif;color:#f5f5f4;background:rgba(28,25,23,.97);border:1px solid rgba(245,158,11,.6);border-radius:10px;padding:10px 14px;box-shadow:0 8px 28px rgba(0,0,0,.4);display:flex;flex-direction:column;gap:8px}
#dsh-safe-banner .dsh-safe-title{display:flex;align-items:center;gap:8px;font-weight:600;color:#fbbf24}
#dsh-safe-banner .dsh-safe-body{opacity:.95;word-break:break-all}
#dsh-safe-banner .dsh-safe-actions{display:flex;gap:8px;flex-wrap:wrap}
#dsh-safe-banner button{cursor:pointer;border-radius:6px;padding:4px 10px;font-size:12px;border:1px solid rgba(255,255,255,.25);background:rgba(255,255,255,.08);color:#fff}
#dsh-safe-banner button:hover{background:rgba(255,255,255,.16)}
#dsh-safe-banner .dsh-safe-heal{background:#f59e0b;border-color:#f59e0b;color:#1c1917;font-weight:600}
#dsh-safe-banner .dsh-safe-heal:hover{background:#fbbf24}
#dsh-safe-banner .dsh-safe-remove{color:#fca5a5}
#dsh-safe-banner .dsh-safe-err{color:#fca5a5;font-size:12px;min-height:1em}
#dsh-safe-banner .dsh-safe-close{margin-left:auto;background:none;border:none;color:rgba(255,255,255,.5);font-size:14px;padding:0 2px}
#dsh-safe-banner .dsh-safe-close:hover{color:#fff;background:none}
</style>
`

// 注意: 注入脚本里不能出现 '</script>' 字样,也不使用模板字符串,
// 避免与宿主模板串冲突(全部字符串拼接)。
const BANNER_SCRIPT = `
<script data-dsh-safe-mode="banner">
(function () {
  try {
    var KEY = 'dsh-safe-banner-collapsed';
    if (typeof sessionStorage !== 'undefined' && sessionStorage.getItem(KEY)) return;
    function esc(s) { return String(s).replace(/[&<>"']/g, function (c) { return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]; }); }
    function boot() {
      fetch('/dsh-safe/status', { cache: 'no-store' }).then(function (r) { return r.ok ? r.json() : null; }).then(function (s) {
        if (!s || !Array.isArray(s.quarantined) || s.quarantined.length === 0) return;
        var root = document.createElement('div');
        root.id = 'dsh-safe-banner';
        var items = s.quarantined.map(function (q) { return esc(q.pkg) + (q.reason ? '：' + esc(q.reason) : ''); });
        var html = '';
        html += '<div class="dsh-safe-title"><span>⚠️</span><span>安全模式</span><span style="flex:1"></span><button class="dsh-safe-close" title="收起本次会话">✕</button></div>';
        html += '<div class="dsh-safe-body">以下插件因加载失败已被自动隔离：<br><b>' + items.join('<br>') + '</b><br><span style="opacity:.75">修好源码后点「解除隔离并重启」；不想修就直接移除。</span></div>';
        html += '<div class="dsh-safe-actions">';
        html += '<button class="dsh-safe-heal">' + (s.quarantined.length > 1 ? '全部解除隔离并重启' : '解除隔离并重启') + '</button>';
        html += s.quarantined.map(function (q) { return '<button class="dsh-safe-remove" data-pkg="' + esc(q.pkg) + '">移除 ' + esc(q.pkg) + '</button>'; }).join('');
        html += '</div><div class="dsh-safe-err"></div>';
        root.innerHTML = html;
        var err = root.querySelector('.dsh-safe-err');
        function act(url, body, label) {
          err.textContent = label + '…';
          fetch(url, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) })
            .then(function (r) { return r.json().catch(function () { return {}; }).then(function (j) { return { r: r, j: j }; }); })
            .then(function (t) {
              if (t.r.ok) { err.textContent = '正在重启 DSH…'; setTimeout(function () { location.reload(); }, 1500); }
              else { err.textContent = '失败: ' + ((t.j && t.j.error) || t.r.status); }
            })
            .catch(function (e) { err.textContent = '请求失败: ' + e; });
        }
        root.querySelector('.dsh-safe-heal').addEventListener('click', function () { act('/dsh-safe/heal', { all: true }, '正在解除隔离'); });
        Array.prototype.forEach.call(root.querySelectorAll('.dsh-safe-remove'), function (b) {
          b.addEventListener('click', function () { act('/dsh-safe/remove', { pkg: b.getAttribute('data-pkg') }, '正在移除'); });
        });
        root.querySelector('.dsh-safe-close').addEventListener('click', function () { try { sessionStorage.setItem(KEY, '1'); } catch (e) {} root.remove(); });
        document.body.appendChild(root);
      }).catch(function () {});
    }
    if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot);
    else boot();
  } catch (e) { console.error('[dsh-safe-mode] banner failed', e); }
})();
</script>
`

function injectBanner(html) {
  const chunk = BANNER_CSS + BANNER_SCRIPT
  return html.includes('</head>') ? html.replace('</head>', chunk + '</head>') : chunk + html
}

// ── 插件主体 ─────────────────────────────────────────────────────────────────
export function apply(ctx) {
  const webServer = ctx.get('webServer')
  if (webServer === undefined) return
  const p = paths(ctx)
  const disposers = []

  const register = (path, handler) => {
    try {
      const dispose = webServer.register({ kind: 'exact', path, handler })
      disposers.push(dispose)
    } catch (e) {
      log('register failed: ' + path + ' ' + String(e))
    }
  }

  register('/dsh-safe/status', async (req, res) => {
    try {
      if (req.method !== 'GET') return sendJson(res, 405, { ok: false, error: 'method not allowed' })
      sendJson(res, 200, computeStatus(p))
    } catch (e) {
      sendJson(res, 500, { ok: false, error: String(e) })
    }
  })

  register('/dsh-safe/heal', async (req, res) => {
    try {
      if (req.method !== 'POST') return sendJson(res, 405, { ok: false, error: 'method not allowed' })
      const body = await readBody(req)
      const state = readState(p.state)
      const ids = readOverlayIds(p.overlay)
      const targets = body.all === true ? ids : [body.id].filter(Boolean)
      if (targets.length === 0) return sendJson(res, 400, { ok: false, error: '没有需要解除的隔离项' })

      // 逐个做语法体检: 仍然损坏的拒绝解除,避免一重启又崩
      for (const id of targets) {
        const entry = (state.quarantined || []).find((q) => q.id === id)
        if (!entry?.pkg || entry.pkg === id) continue // 未知来源,放行
        const check = checkPluginSyntax(entry.pkg, p.profileDir)
        if (!check.ok) return sendJson(res, 422, { ok: false, id, error: `${entry.pkg} 仍然损坏: ${check.err}` })
      }

      const remaining = ids.filter((id) => !targets.includes(id))
      writeOverlay(p.overlay, remaining)
      writeState(p.state, (state.quarantined || []).filter((q) => !targets.includes(q.id)))
      log('healed: ' + targets.join(', '))
      sendJson(res, 200, { ok: true, healed: targets })
      restartSoon()
    } catch (e) {
      sendJson(res, 500, { ok: false, error: String(e) })
    }
  })

  register('/dsh-safe/remove', async (req, res) => {
    try {
      if (req.method !== 'POST') return sendJson(res, 405, { ok: false, error: 'method not allowed' })
      const body = await readBody(req)
      const pkg = typeof body.pkg === 'string' ? body.pkg.trim() : ''
      if (!/^[A-Za-z0-9@/._-]+$/.test(pkg) || pkg.length > 100) {
        return sendJson(res, 400, { ok: false, error: '非法包名' })
      }
      // 先回答浏览器,再跑 dsh plugin remove(pnpm 可能耗时数秒),完成后重启
      sendJson(res, 200, { ok: true, removing: pkg })
      log('removing: ' + pkg)
      const child = spawn('dsh', ['plugin', '--profile', p.profileName, 'remove', pkg], {
        detached: true,
        stdio: ['ignore', 'pipe', 'pipe'],
        env: process.env
      })
      let out = ''
      child.stdout?.on('data', (d) => { out += d })
      child.stderr?.on('data', (d) => { out += d })
      child.on('exit', (code) => {
        log(`remove exit=${code} out=${out.slice(0, 500)}`)
        // 顺带清掉隔离记录(若它在隔离清单里)
        try {
          const ids = readOverlayIds(p.overlay)
          const state = readState(p.state)
          const idx = (state.quarantined || []).findIndex((q) => q.pkg === pkg)
          if (idx >= 0) {
            const q = state.quarantined[idx]
            writeOverlay(p.overlay, ids.filter((id) => id !== q.id))
            writeState(p.state, state.quarantined.filter((_, i) => i !== idx))
          }
        } catch (e) {
          log('cleanup failed: ' + String(e))
        }
        restartSoon()
      })
      child.on('error', (e) => log('remove spawn error: ' + e.message))
    } catch (e) {
      sendJson(res, 500, { ok: false, error: String(e) })
    }
  })

  try {
    const disposeTap = webServer.tapIndex(injectBanner)
    disposers.push(disposeTap)
  } catch (e) {
    log('tapIndex failed: ' + String(e))
  }

  ctx.effect(() => {
    for (const d of disposers) {
      try {
        d()
      } catch {
        /* 忽略单个清理失败 */
      }
    }
  }, NAME + ': routes')
  log('ready')
}

export const inject = ['webServer']
