// dsh-safe-mode host half — 安全模式便签面板。
//
// 背景: 当某个插件的 host 代码(lib/index.js)被改坏时,dsh 的 Loader 会
// 整体回滚启动(任一条目失败 = 整棵树失败),用户连 Web 界面都进不去。
// dsh-safe 脚本 / dsh 透明包装器(dsh-wrapper)会在启动失败时把坏插件写入
// ~/.dsh/profiles/<profile>/safe-mode.overlay.yml(格式为 patch 覆盖层,
// `- id: xxx / disabled: true`),然后以 `dsh web --patch <overlay> --port 9527`
// 启动安全模式: 被隔离的条目 disabled=true,Loader 连它的模块都不会 import,
// 坏插件不影响启动。
//
// 本插件负责安全模式下的「界面」—— 右下角便签(类似贴纸,一直悬挂,
// 除非手动关闭;关闭后可从小圆钮重新打开):
//   * 告知当前模式(安全模式)与端口;
//   * 列出问题插件与原因(来自 /dsh-safe/status);
//   * 「📋 复制诊断」按钮 —— 复制一份完整诊断报告;
//   * 「解除隔离并重启」(先做语法体检,仍坏则拒绝)与「移除」入口;
// 路由:
//   GET  /dsh-safe/status   查询隔离状态;
//   POST /dsh-safe/heal     {all:true} 或 {id} —— 解除隔离(先做语法体检)并重启;
//   POST /dsh-safe/remove   {pkg} —— 从 profile 移除该插件并重启。
//
// 自愈: 启动时序竞争(webserver 行可能重建,导致本插件注册在旧实例上)会
// 让路由/注入偶尔失效 —— apply 内自检通过但实际请求 404。因此这里每 2 秒
// 重新获取 webServer 实例并补齐注册(幂等,已存在则跳过)。
//
// ⚠️ 本插件是全仓库「最不该被 AI 修改」的文件之一: 它自身若损坏,
// 安全模式就没有界面了。代码刻意保持简单、防御式(所有路由 try/catch)。
import { spawn, spawnSync } from 'node:child_process'
import { appendFileSync, existsSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const NAME = 'dsh-safe-mode'
const DIAG = '/tmp/dsh-safe-mode.log'
const HEAL_MS = 2000 // 自愈间隔

function log(...parts) {
  try {
    appendFileSync(DIAG, `${new Date().toISOString()} ${parts.join(' ')}\n`, 'utf8')
  } catch {
    /* 日志失败不影响功能 */
  }
}

// ── 路径 ─────────────────────────────────────────────────────────────────────
function paths(ctx) {
  const homePath = ctx.get('dshHomePath')
  const profileName = process.env.DSH_SAFE_PROFILE || 'web'
  let profileDir
  try {
    // dshHomePath(...segments) = <DSH_HOME>/<segments>,由 dsh-app-boot 提供
    profileDir = typeof homePath === 'function'
      ? homePath('profiles', profileName)
      : join(process.env.DSH_HOME || process.env.HOME || '', '.dsh', 'profiles', profileName)
  } catch {
    profileDir = join(process.env.DSH_HOME || process.env.HOME || '', '.dsh', 'profiles', profileName)
  }
  return {
    profileName,
    profileDir,
    overlay: join(profileDir, 'safe-mode.overlay.yml'),
    state: join(profileDir, 'safe-mode.state.json')
  }
}

// ── 隔离文件读写 ─────────────────────────────────────────────────────────────
// overlay 是 dsh 真正读取的文件(patch 覆盖层): 每条 `- id: xxx / disabled: true`
// 对应一个被隔离的 bundle 行。state 是给本插件/脚本看的 JSON(记录原因、时间)。
// 注意: overlay 永远不删除,空时写 '[]'(若删除,而进程是以 --patch <它> 启动的,
// 重启按钮会因文件缺失而启动失败)。
function readOverlayIds(file) {
  if (!existsSync(file)) return []
  const text = readFileSync(file, 'utf8')
  const ids = []
  for (const m of text.matchAll(/^\s*(?:-\s*)?id:\s*([^\s#]+)/gm)) ids.push(m[1].trim())
  return ids
}

function writeOverlay(file, ids) {
  const head = '# dsh-safe quarantine overlay — generated by dsh-safe / dsh-safe-mode. Do not edit by hand.\n'
  if (ids.length === 0) {
    writeFileSync(file, head + '[]\n', 'utf8')
    return
  }
  // patch 格式: 非 insert 条目 = 顶层 id + 覆盖字段(与 loader 写回 / dsh-plugin-manager
  // 持久化的格式一致;没有 `edit:` 包装层)
  writeFileSync(file, head + ids.map((id) => `- id: ${id}\n  disabled: true`).join('\n') + '\n', 'utf8')
}

function readState(file) {
  try {
    return JSON.parse(readFileSync(file, 'utf8'))
  } catch {
    return { quarantined: [] }
  }
}

function writeState(file, quarantined) {
  writeFileSync(file, JSON.stringify({ quarantined, updatedAt: new Date().toISOString() }, null, 2) + '\n', 'utf8')
}

// ── 语法体检(解除隔离前的安全检查) ─────────────────────────────────────────
function checkJs(file) {
  const r = spawnSync(process.execPath, ['--check', file], { encoding: 'utf8' })
  if (r.status === 0) return { ok: true }
  // ESM 兜底: 部分 node 版本 --check 按 CJS 解析,换 stdin + --input-type=module 再试
  let src
  try {
    src = readFileSync(file, 'utf8')
  } catch {
    return { ok: false, err: `无法读取 ${file}` }
  }
  const r2 = spawnSync(process.execPath, ['--check', '--input-type=module'], { input: src, encoding: 'utf8' })
  if (r2.status === 0) return { ok: true }
  const err = (r2.stderr || r.stderr || '').split('\n').find(Boolean) || 'syntax error'
  return { ok: false, err: err.slice(0, 300) }
}

function checkPluginSyntax(pkg, profileDir) {
  const dir = join(profileDir, 'node_modules', pkg)
  if (!existsSync(dir)) return { ok: true } // 包已不在,无需体检
  let manifest
  try {
    manifest = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8'))
  } catch (e) {
    return { ok: false, err: `package.json 解析失败: ${e.message}` }
  }
  const mainRel = manifest.main || 'lib/index.js'
  const mainPath = join(dir, mainRel)
  if (existsSync(mainPath)) {
    const r = checkJs(mainPath)
    if (!r.ok) return { ok: false, err: `${mainRel} 语法错误: ${r.err}` }
  } else if (manifest.main) {
    return { ok: false, err: `main 文件不存在: ${mainRel}` }
  }
  const clientPath = join(dir, 'lib/client.js')
  if (existsSync(clientPath)) {
    const r = checkJs(clientPath)
    if (!r.ok) return { ok: false, err: `lib/client.js 语法错误: ${r.err}` }
  }
  return { ok: true }
}

// ── HTTP 工具 ────────────────────────────────────────────────────────────────
function sendJson(res, code, obj) {
  const body = JSON.stringify(obj)
  try {
    res.writeHead(code, {
      'Content-Type': 'application/json; charset=utf-8',
      'Content-Length': Buffer.byteLength(body)
    })
    res.end(body)
  } catch {
    /* 连接已断开 */
  }
}

function readBody(req) {
  return new Promise((resolve, reject) => {
    let data = ''
    req.on('data', (chunk) => {
      data += chunk
      if (data.length > 64 * 1024) {
        req.destroy()
        reject(new Error('body too large'))
      }
    })
    req.on('end', () => {
      try {
        resolve(data ? JSON.parse(data) : {})
      } catch (e) {
        reject(e)
      }
    })
    req.on('error', reject)
  })
}

// ── 重启(与 dsh-system-restart 同款: 回答浏览器后拉新进程再退出) ───────────
function restartSoon() {
  setTimeout(() => {
    try {
      log('restarting: argv=' + process.argv.slice(1).join(' '))
      const child = spawn(process.execPath, process.argv.slice(1), {
        detached: true,
        stdio: 'inherit',
        env: process.env,
        cwd: process.cwd()
      })
      child.unref()
    } catch (error) {
      log('restart failed: ' + (error instanceof Error ? error.message : String(error)))
    }
    process.exit(0)
  }, 800)
}

// ── 状态计算 ─────────────────────────────────────────────────────────────────
function computeStatus(p) {
  const ids = readOverlayIds(p.overlay)
  const state = readState(p.state)
  const quarantined = ids.map((id) => {
    const s = (state.quarantined || []).find((q) => q.id === id)
    return { id, pkg: s?.pkg || id, reason: s?.reason || '', at: s?.at || '' }
  })
  return { ok: true, profile: p.profileName, overlayExists: existsSync(p.overlay), quarantined }
}

// ── 便签注入(tapIndex,不依赖 slot/客户端模块) ─────────────────────────────
// 右下角便签: 一直悬挂,除非用户关闭(关闭后保留一个小圆钮可重新打开)。
const NOTE_CSS = `
<style data-dsh-safe-mode="note">
#dsh-safe-note{position:fixed;right:16px;bottom:16px;z-index:2147483000;width:320px;box-sizing:border-box;font:13px/1.55 -apple-system,BlinkMacSystemFont,'Segoe UI','PingFang SC','Microsoft YaHei',sans-serif;color:#f5f5f4;background:rgba(35,30,20,.97);border:1px solid rgba(245,158,11,.55);border-top:3px solid #f59e0b;border-radius:10px;padding:12px 14px;box-shadow:0 10px 32px rgba(0,0,0,.45);display:flex;flex-direction:column;gap:8px}
#dsh-safe-note .dsn-top{display:flex;align-items:center;gap:8px}
#dsh-safe-note .dsn-badge{font-weight:700;color:#fbbf24}
#dsh-safe-note .dsn-close{margin-left:auto;background:none;border:none;color:rgba(255,255,255,.5);font-size:14px;cursor:pointer;padding:0 2px}
#dsh-safe-note .dsn-close:hover{color:#fff}
#dsh-safe-note .dsn-mode{opacity:.85}
#dsh-safe-note .dsn-label{opacity:.7;margin:2px 0 4px}
#dsh-safe-note .dsn-item{background:rgba(255,255,255,.06);border-left:2px solid #f87171;border-radius:4px;padding:5px 8px;margin-bottom:5px;word-break:break-all}
#dsh-safe-note .dsn-item-name{font-weight:600;color:#fca5a5}
#dsh-safe-note .dsn-item-reason{opacity:.85;font-size:12px;white-space:pre-wrap}
#dsh-safe-note .dsn-actions{display:flex;gap:8px;flex-wrap:wrap}
#dsh-safe-note button{cursor:pointer;border-radius:6px;padding:5px 10px;font-size:12px;border:1px solid rgba(255,255,255,.25);background:rgba(255,255,255,.08);color:#fff}
#dsh-safe-note button:hover{background:rgba(255,255,255,.16)}
#dsh-safe-note .dsn-heal{background:#f59e0b;border-color:#f59e0b;color:#1c1917;font-weight:600}
#dsh-safe-note .dsn-heal:hover{background:#fbbf24}
#dsh-safe-note .dsn-err{color:#fca5a5;font-size:12px;min-height:1em}
#dsh-safe-reopen{position:fixed;right:16px;bottom:16px;z-index:2147483000;width:38px;height:38px;border-radius:50%;border:1px solid rgba(245,158,11,.6);background:rgba(35,30,20,.95);color:#fbbf24;font-size:17px;cursor:pointer;box-shadow:0 4px 14px rgba(0,0,0,.4)}
#dsh-safe-reopen:hover{background:rgba(60,50,30,.98)}
</style>
`

// 注意: 注入脚本里不能出现 '</script>' 字样,也不使用模板字符串,
// 避免与宿主模板串冲突(全部字符串拼接)。
const NOTE_SCRIPT = `
<script data-dsh-safe-mode="note">
(function () {
  try {
    var HIDE_KEY = 'dsh-safe-note-hidden';
    function esc(s) { return String(s).replace(/[&<>"']/g, function (c) { return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]; }); }
    function fmtTime(ts) { try { return new Date(ts).toLocaleString('zh-CN', { hour12: false }); } catch (e) { return String(ts); } }
    function copyText(text) {
      function fallback() {
        try {
          var ta = document.createElement('textarea');
          ta.value = text; ta.style.position = 'fixed'; ta.style.opacity = '0';
          document.body.appendChild(ta); ta.select();
          document.execCommand('copy');
          document.body.removeChild(ta);
        } catch (e) {}
      }
      if (navigator.clipboard && navigator.clipboard.writeText) navigator.clipboard.writeText(text).catch(fallback);
      else fallback();
    }
    function buildReport(s) {
      var lines = [];
      lines.push('DSH 安全模式诊断报告');
      lines.push('════════════════════════');
      lines.push('时间: ' + fmtTime(Date.now()));
      lines.push('模式: 安全模式' + (s.profile ? ' (profile: ' + s.profile + ')' : ''));
      lines.push('问题插件: ' + s.quarantined.length + ' 个');
      s.quarantined.forEach(function (q, i) {
        lines.push('  ' + (i + 1) + '. ' + q.pkg + ' (行 id: ' + q.id + ')');
        if (q.reason) lines.push('     原因: ' + q.reason);
      });
      lines.push('');
      lines.push('修复建议:');
      lines.push('  1. 修复插件源码后,点便签上的「解除隔离并重启」');
      lines.push('  2. 或运行: dsh-safe heal --all');
      lines.push('  3. 或移除插件: dsh plugin --profile ' + (s.profile || 'web') + ' remove <包名>');
      return lines.join('\\n');
    }
    function renderNote(s) {
      var root = document.createElement('div');
      root.id = 'dsh-safe-note';
      var items = '';
      s.quarantined.forEach(function (q) {
        items += '<div class="dsn-item"><div class="dsn-item-name">' + esc(q.pkg) + '</div>' +
          (q.reason ? '<div class="dsn-item-reason">' + esc(q.reason) + '</div>' : '') + '</div>';
      });
      root.innerHTML =
        '<div class="dsn-top"><span class="dsn-badge">🛟 安全模式</span><button class="dsn-close" title="关闭便签(可点右下角小圆钮重新打开)">✕</button></div>' +
        '<div class="dsn-mode">当前模式: 安全模式</div>' +
        '<div class="dsn-plugins"><div class="dsn-label">问题插件 (' + s.quarantined.length + '):</div>' + items + '</div>' +
        '<div class="dsn-actions">' +
        '<button class="dsn-copy">📋 复制诊断</button>' +
        '<button class="dsn-heal">解除隔离并重启</button>' +
        '</div><div class="dsn-err"></div>';
      document.body.appendChild(root);
      var err = root.querySelector('.dsn-err');
      root.querySelector('.dsn-copy').addEventListener('click', function () {
        copyText(buildReport(s));
        err.textContent = '已复制到剪贴板 ✓';
      });
      root.querySelector('.dsn-heal').addEventListener('click', function () {
        err.textContent = '正在解除隔离并重启…';
        fetch('/dsh-safe/heal', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ all: true }) })
          .then(function (r) { return r.json().catch(function () { return {}; }).then(function (j) { return { r: r, j: j }; }); })
          .then(function (t) {
            if (t.r.ok) { err.textContent = '已解除,正在重启…'; setTimeout(function () { location.reload(); }, 1500); }
            else { err.textContent = '失败: ' + ((t.j && t.j.error) || t.r.status); }
          })
          .catch(function (e) { err.textContent = '请求失败: ' + e; });
      });
      root.querySelector('.dsn-close').addEventListener('click', function () {
        try { sessionStorage.setItem(HIDE_KEY, '1'); } catch (e) {}
        root.remove();
        showReopen();
      });
    }
    function showReopen() {
      if (document.getElementById('dsh-safe-reopen')) return;
      var btn = document.createElement('button');
      btn.id = 'dsh-safe-reopen';
      btn.title = '安全模式信息';
      btn.textContent = '🛟';
      btn.addEventListener('click', function () {
        try { sessionStorage.removeItem(HIDE_KEY); } catch (e) {}
        btn.remove();
        fetchStatus();
      });
      document.body.appendChild(btn);
    }
    // 等待 dsh 界面完全渲染(侧边栏根元素出现 + #root 有内容)再渲染便签;
    // 最长等 15 秒兜底(即使类名模式失效,便签最多晚 15 秒,不会丢失)
    function waitForUi(cb) {
      var tries = 0;
      var check = function () {
        tries++;
        var sidebar = document.querySelector('[class*="Xa_root"]');
        var root = document.getElementById('root');
        var uiReady = sidebar && root && root.children.length > 0;
        if (uiReady || tries > 50) { setTimeout(cb, 1500); }
        else { setTimeout(check, 300); }
      };
      check();
    }
    // 轮询取状态: 无隔离/请求失败 → 3 秒后重试(等自愈补齐路由);有隔离 → 等 UI 就绪再渲染
    function fetchStatus() {
      fetch('/dsh-safe/status', { cache: 'no-store' })
        .then(function (r) { return r.ok ? r.json() : null; })
        .then(function (s) {
          if (!s || !Array.isArray(s.quarantined) || s.quarantined.length === 0) {
            setTimeout(fetchStatus, 3000);
            return;
          }
          waitForUi(function () {
            var hidden = false;
            try { hidden = sessionStorage.getItem(HIDE_KEY) === '1'; } catch (e) {}
            if (hidden) showReopen(); else renderNote(s);
          });
        })
        .catch(function () { setTimeout(fetchStatus, 3000); });
    }
    if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', fetchStatus);
    else fetchStatus();
  } catch (e) { console.error('[dsh-safe-mode] note failed', e); }
})();
</script>
`

function injectBanner(html) {
  const chunk = NOTE_CSS + NOTE_SCRIPT
  return html.includes('</head>') ? html.replace('</head>', chunk + '</head>') : chunk + html
}

// ── 插件主体 ─────────────────────────────────────────────────────────────────
export function apply(ctx) {
  const webServer = ctx.get('webServer')
  if (webServer === undefined) return
  const p = paths(ctx)

  const handlers = {
    '/dsh-safe/status': async (req, res) => {
      try {
        if (req.method !== 'GET') return sendJson(res, 405, { ok: false, error: 'method not allowed' })
        sendJson(res, 200, computeStatus(p))
      } catch (e) {
        sendJson(res, 500, { ok: false, error: String(e) })
      }
    },
    '/dsh-safe/heal': async (req, res) => {
      try {
        if (req.method !== 'POST') return sendJson(res, 405, { ok: false, error: 'method not allowed' })
        const body = await readBody(req)
        const state = readState(p.state)
        const ids = readOverlayIds(p.overlay)
        const targets = body.all === true ? ids : [body.id].filter(Boolean)
        if (targets.length === 0) return sendJson(res, 400, { ok: false, error: '没有需要解除的隔离项' })

        // 逐个做语法体检: 仍然损坏的拒绝解除,避免一重启又崩
        for (const id of targets) {
          const entry = (state.quarantined || []).find((q) => q.id === id)
          if (!entry?.pkg || entry.pkg === id) continue // 未知来源,放行
          const check = checkPluginSyntax(entry.pkg, p.profileDir)
          if (!check.ok) return sendJson(res, 422, { ok: false, id, error: `${entry.pkg} 仍然损坏: ${check.err}` })
        }

        const remaining = ids.filter((id) => !targets.includes(id))
        writeOverlay(p.overlay, remaining)
        writeState(p.state, (state.quarantined || []).filter((q) => !targets.includes(q.id)))
        log('healed: ' + targets.join(', '))
        sendJson(res, 200, { ok: true, healed: targets })
        restartSoon()
      } catch (e) {
        sendJson(res, 500, { ok: false, error: String(e) })
      }
    },
    '/dsh-safe/remove': async (req, res) => {
      try {
        if (req.method !== 'POST') return sendJson(res, 405, { ok: false, error: 'method not allowed' })
        const body = await readBody(req)
        const pkg = typeof body.pkg === 'string' ? body.pkg.trim() : ''
        if (!/^[A-Za-z0-9@/._-]+$/.test(pkg) || pkg.length > 100) {
          return sendJson(res, 400, { ok: false, error: '非法包名' })
        }
        // 先回答浏览器,再跑 dsh plugin remove(pnpm 可能耗时数秒),完成后重启
        sendJson(res, 200, { ok: true, removing: pkg })
        log('removing: ' + pkg)
        const child = spawn('dsh', ['plugin', '--profile', p.profileName, 'remove', pkg], {
          detached: true,
          stdio: ['ignore', 'pipe', 'pipe'],
          env: process.env
        })
        let out = ''
        child.stdout?.on('data', (d) => { out += d })
        child.stderr?.on('data', (d) => { out += d })
        child.on('exit', (code) => {
          log(`remove exit=${code} out=${out.slice(0, 500)}`)
          // 顺带清掉隔离记录(若它在隔离清单里)
          try {
            const ids = readOverlayIds(p.overlay)
            const state = readState(p.state)
            const idx = (state.quarantined || []).findIndex((q) => q.pkg === pkg)
            if (idx >= 0) {
              const q = state.quarantined[idx]
              writeOverlay(p.overlay, ids.filter((id) => id !== q.id))
              writeState(p.state, state.quarantined.filter((_, i) => i !== idx))
            }
          } catch (e) {
            log('cleanup failed: ' + String(e))
          }
          restartSoon()
        })
        child.on('error', (e) => log('remove spawn error: ' + e.message))
      } catch (e) {
        sendJson(res, 500, { ok: false, error: String(e) })
      }
    }
  }

  // 幂等注册: 路由/tapIndex 缺失才补(自愈时重新拿 webServer,规避实例替换)
  const ensureRegistered = () => {
    const ws = ctx.get('webServer')
    if (!ws) return
    for (const [path, handler] of Object.entries(handlers)) {
      try {
        if (ws.match(path) === undefined) {
          ws.register({ kind: 'exact', path, handler })
          log('heal: registered ' + path)
        }
      } catch (e) {
        log('heal error ' + path + ' ' + String(e))
      }
    }
    try {
      if (!ws.applyIndexTaps('<html></html>').includes('dsh-safe-note')) {
        ws.tapIndex(injectBanner)
        log('heal: tapIndex re-registered')
      }
    } catch (e) {
      log('heal tap error ' + String(e))
    }
  }

  ensureRegistered()
  const timer = setInterval(ensureRegistered, HEAL_MS)
  timer.unref?.()
  ctx.effect(() => {
    clearInterval(timer)
  }, NAME + ': heal-timer')
  log('ready')
}

export const inject = ['webServer']
